### ISSUE TITLE
Add Internship

### ISSUE THREAD

**Issue by cheseuca** [ella-emc/ph-tech-internships#1]
### Link to Internship Posting

https://www.rappler.com/moveph/263-rappler-internship-program-careers/

### Company Name

Rappler

### Link to company's homepage

https://www.rappler.com/

### Internship role and/or Program Name

IT Intern

### Location

Pasig | Hybrid

### Where is the company based?

Philippines

### Is this internship open to international (non-Filipino) applicants?

None

### Is this internship open to Filipino/foreign applicants?

None

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

chescarellano@gmail.com

### Extra Notes (Optional)

Hello, I hope this finds you well and hoping that this repo is currently active. So I found this internship program from Rappler and they offer to students in any field including IT technology, it was indicated in their social media post that it has programming or working on data(?) for the IT intern role.  Also the deadline is until July 31, and they plan to onboard the interns in August to October
![Screenshot 2024-07-18 001952](https://github.com/user-attachments/assets/4d8822a6-7cb5-498e-b781-61d65051f662)

**Comment by ella-emc** [comment]
Hello Chesca,

I'll work on adding this to the master list at my earliest convenience. Thank you for your contribution!
