### ISSUE TITLE
Add Internship

### ISSUE THREAD

**Issue by Itsmeejoshiee** [ella-emc/ph-tech-internships#3]
### Link to Internship Posting

https://education.github.com/students/octernships

### Company Name

Github

### Link to company's homepage

https://education.github.com

### Internship role and/or Program Name

Github Octernships

### Location

Remote

### Where is the company based?

Abroad

### Application deadline

Open year-round

### Is this internship open to international (non-Filipino) applicants?

Yes

### Is this internship open to Filipino/foreign applicants?

Yes

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

joshgorospe03@gmail.com

### Extra Notes (Optional)

Eligibility for Github Octernships:

-18+ Years Old
-Verified Student on Github Global Campus
-An active contributor on Github
-Enrolled in an institution with work eligibility in one of the ten countries: India, Singapore, Indonesia, Malaysia, Vietnam, Philippines, Thailand, Mexico, Nigeria, and Colombia.

**Comment by ella-emc** [comment]
Hi Josh! Thanks for contributing, but the link to the internship posting is not working.

**Comment by Itsmeejoshiee** [comment]
Good afternoon ella! I think Github Octernship is currently closed.  I'm not sure the reason why since it's an all-year round program. I'm pretty sure they'll reopen soon

**Comment by ella-emc** [comment]
Alright, I'll add this with remarks as to its status. 

Thanks again for the contribution!
